sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mzeithaml/docker-react -f Dockerfile.dev .

script:
  - docker run  mzeithaml/docker-react npm run test -- --coverage
